### ISSUE TITLE
Migrate to Material 3

### ISSUE THREAD

**Issue by sunkup** [ArnyminerZ/icsx5#107]
- [x] [compose-material-dialogs](https://github.com/PranavMaganti/compose-material-dialogs/tree/main) uses M2, and seems that is no longer maintained, so we ~might~ **want** to move away from it. 
  - [X] Follow [Migration guide](https://developer.android.com/jetpack/compose/designsystems/material2-material3)
  - [x] Fix light theme colors
  - [x] Fix dark theme colors 
  - [x] use M3's [`supportingText` param on textfields](https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#textfield) to show examples or hints like "Field is required" and error messages for invalid input 

_Note:_ ~We can't get rid of the M2 dependency yet, as pullRefresh (new name [pullToRefresh](https://developer.android.com/reference/kotlin/androidx/compose/material3/pulltorefresh/package-summary)) has not been migrated yet. Its in beta already though.~

**Comment by ArnyminerZ** [comment]
If I'm not wrong, pull to refresh was released with Material 3 [1.2.0](https://developer.android.com/jetpack/androidx/releases/compose-material3#1.2.0)
